import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState, useEffect, useContext } from "react";
import { getOneUserMeta } from "../lib/getOneUserMeta";
import Result from "../components/Results";
import { ACTION_TYPES, UserContext } from "../context/github-user-context";
import { Input } from "antd";
import { Spin } from "antd";
import { UserOutlined } from "@ant-design/icons";
import { useRouter } from "next/router";
import useDebounce from "../hooks/useDebounce";

export default function Home() {
  const { indexPageState, dispatch } = useContext(UserContext);
  const [inputUserName, setUserName] = useState(() =>
    indexPageState?.inputUserName ? indexPageState.inputUserName : ""
  );
  const [returnObj, setReturnObj] = useState("");
  const [loading, setLoading] = useState(false);
  const [debounceTime, setDebounceTime] = useState(0);
  const router = useRouter();
  const debounce = useDebounce(inputUserName, debounceTime);
  const handleNameInput = (e) => {
    setUserName(e?.target?.value);
  };

  const fetchPicAndName = async () => {
    if (inputUserName === "") {
      setReturnObj("");
    } else {
      if (loading) {
        return;
      }
      setLoading(true);
      const returnPicAndName = await getOneUserMeta(inputUserName);
      console.log(returnPicAndName);
      setReturnObj(returnPicAndName);
      setLoading(false);
    }
  };

  useEffect(() => {
    if (debounce) {
      fetchPicAndName();
    }
  }, [debounce, debounceTime]);
  useEffect(() => {
    if (inputUserName === "") {
      setDebounceTime(0);
      console.log(0);
      setReturnObj("");
      setUserName("");
      console.log("HI");
    } else {
      console.log(700);
      setDebounceTime(700);
    }
  }, [inputUserName]);
  const examineUndefined = (meta) => {
    if (typeof meta !== "undefined" && typeof meta.data !== "undefined") {
      return true;
    }
    return false;
  };

  useEffect(() => {
    setUserName(sessionStorage.getItem("inputUserName"));
    // console.log("hi");
    console.log(indexPageState.inputUserName);
  }, [router]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.transForm}>
          <div className={styles.inputBox}>
            <Input
              placeholder="find a user"
              prefix={<UserOutlined />}
              value={inputUserName}
              onChange={handleNameInput}
              size="large"
            />
          </div>

          <div
            className={`${styles.resultCardContainer} ${
              loading && styles.spinContainer
            }`}
          >
            {inputUserName === "" ? (
              <div className={styles.searchPic}>
                <Image src="/img/search.png" width={230} height={230}></Image>
              </div>
            ) : loading ? (
              <Spin size="large" />
            ) : (
              <Result
                href={`users/${inputUserName}/repos`}
                inputUserName={inputUserName}
                meta={returnObj}
                debounce={debounce}
              ></Result>
            )}
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
