import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
// import { Octokit } from "@octokit/core";
import getOneUserMeta from "../lib/getOneUserMeta";
export default function Home() {
  const [userName, setUserName] = useState("");
  const [returnObj, setReturnObj] = useState("");
  // const [trys, setTry] = useState("");
  const handleNameInput = (e) => {
    setUserName(e.target.value);
  };

  // const octokit = new Octokit({
  //   auth: `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`,
  // });
  // useEffect(() => {
  //   const trytry = async () => {
  //     try {
  //       const res = await octokit.request("GET /users");
  //       setTry(trys);
  //     } catch (error) {
  //       console.error("Some thing wrong");
  //     }
  //   };
  //   console.log(trys);
  //   trytry();
  // }, [userName]);

  useEffect(() => {
    console.log(returnObj);
    getOneUserMeta(userName, setReturnObj);
  }, [userName]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
        <div>
          <input
            type="text"
            placeholder="name"
            value={userName}
            onChange={handleNameInput}
          />
          {/* {typeof returnObj !== "undefined" &&
          typeof returnObj.data !== "undefined" &&
          typeof returnObj.data[0] !== "undefined" &&
          typeof returnObj.data[0].id !== "undefined"
            ? <span>returnObj.data[0].id</span> && (
                <img src={`${returnObj.data[0].owner.avatar_url}`} />
              )
            : "no data"} */}

          {typeof returnObj !== "undefined" &&
          typeof returnObj.data !== "undefined" ? (
            <div>
              <p>{returnObj.data.name}</p>
              <img src={returnObj.data.avatar_url} />
            </div>
          ) : (
            "no data"
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
